
@base_url = http://localhost:8082/api
@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJVMDAxIiwiZW1haWwiOiJhQHRlc3QuY29tIiwic3RhdHVzIjoiYWN0aXZlIiwicm9sZSI6InVzZXIiLCJpc3MiOiJkZWJvbGVpYS1iZSIsImV4cGlyZXNJbiI6IjEwMDBoIiwiaWF0IjoxNzM3NjM4MzI1fQ.pJfBUaODGCOn0ja7qCmivGFuDX7TV8JwE_dmL6ZtNB7hVTs6ZanuK2rY2C2zKjzyT8LiKbOZ5l3ljSzQEldJ_T-NlOBLem3J4MwpgHK10jykdMtQBxbLcxjK59mOYeG3gRlNSDzie2_6zKp4dGCTP7DZX-0-lcimDnPRcbKaom82CsckVbOtZiz9gqonHiUegq3zj_k2Gj8uSf0ktAa5a--TX-N36H370-TAXhjNPmBoSOVR1KnMlTQCzTJIkWSc5tSQc9EqmtCbwvFLSnX0P5v7uu0MIH4O5C-Im6jIxxwWYLFgyCCGvphNNV1WBMUeENWPOZ6sECEu3AfpmmReFg
###

GET {{base_url}}/trips
Authorization: Bearer {{token}}

###

POST http://localhost:8082/api/auth/login HTTP/1.1
# Authorization: : oasdfnsaodfoasdnfoaisdoasd
content-type: application/json

{
    "email": "a@test.com",
    "password": "123123123"
}

###

###

POST http://localhost:8082/api/trips HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
  "origin": {
    "district": "Faro",
    "municipality": "Faro",
    "parish": "Montenegro"
  },
  "destination": {
    "district": "Lisboa",
    "municipality": "Oeiras"
  },
  "car": "AA-65-UY",
  "nrSeats": 2,
  "estimatedCost": 50.00,
  "pricePerPerson": 25.00,
  "driver": "U001",
  "departureDate": "2025-05-30T13:30:00.000Z"
}


###

GET {{base_url}}/trips/tripCode/RWFPJ1 HTTP/1.1
Authorization: Bearer {{token}}


###

PATCH {{base_url}}/trips/offer/tripCode/UZT83C HTTP/1.1
Authorization: Bearer {{token}}

###

###

GET {{base_url}}/trips/all HTTP/1.1
Authorization: Bearer {{token}}

###